apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ping-pong-dep
  template:
    metadata:
      labels:
        app: kube-ping-pong-dep
    spec:
      containers:
        - name: kubernetes-ping-pong
          image: nettivastaava/kubernetes-ping-pong:3.2
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-apkey
                  key: POSTGRES_PASSWORD
              
