apiVersion: v1
kind: Service
metadata:
  name: kube-ping-pong-svc
spec:
  type: LoadBalancer
  selector:
    app: kube-ping-pong-dep
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
