apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-project-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-project-dep
  template:
    metadata:
      labels:
        app: todo-project-dep
    spec:
      containers:
        - name: kube-todo-project
          image: nettivastaava/kube-todo-project:0.8 
