apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: log-output-rw-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: log-output-rw
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50