apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: log-output
  name: kube-ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-ping-pong-dep
  template:
    metadata:
      labels:
        app: kube-ping-pong-dep
    spec:
      volumes:
        - name: pongs
          emptyDir: {}
      containers:
        - name: kubernetes-ping-pong
          image: nettivastaava/kubernetes-ping-pong:p2
          volumeMounts:
            - name: pongs 
              mountPath: usr/src/app/files
              
