apiVersion: v1
kind: Service
metadata:
  namespace: log-output
  name: kube-ping-pong-svc
spec:
  type: ClusterIP
  selector:
    app: kube-ping-pong-dep
  ports:
    - port: 2346
      protocol: TCP
      targetPort: 5000
