apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: log-output
  name: pongs-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
