apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: cpu-usage
spec:
  metrics:
  - name: cpu-usage
    initialDelay: 10m
    successCondition: result < 3
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1658-prometheus-0.prometheus.svc:9090
        query: |
          scalar(
            sum(rate(container_cpu_usage_seconds_total{namespace="todo"}[10m])) * 1000
          )